validate params from values.yaml (#197)
# Description
We were only validation params which are present as part of description
(Exposed to user). As a result, params that are hidden but can be
overridden, was not working

# Fix
Validate all params instead of what is exposed

# Testing

Case 1: valid param
```
[root@sagarwal ai-services]# ./bin/ai-services application create temp --template rag --params "ingest.log_level=DEBUG"
Validating the LPAR environment before creating application 'temp'...
Creating application 'temp' using template 'rag'
✔ SMT level configured successfully
No existing pods found for application: temp
Downloading container images required for application template rag:
Downloading image: icr.io/ai-services/tools:0.5...
Pulling image icr.io/ai-services/tools:0.5...
Trying to pull icr.io/ai-services/tools:0.5...
^C

[root@sagarwal ai-services]# ./bin/ai-services application create temp --template rag --params "ui.port=12312"
Validating the LPAR environment before creating application 'temp'...
Creating application 'temp' using template 'rag'
✔ SMT level configured successfully
No existing pods found for application: temp
Downloading container images required for application template rag:
Downloading image: icr.io/ai-services/tools:0.5...
Pulling image icr.io/ai-services/tools:0.5...
^C
```

Case 2: Invalid param
```
[root@sagarwal ai-services]# ./bin/ai-services application create temp --template rag --params "u.port=12312"
Error: failed to load params for application: unsupported parameter: u.port

[root@sagarwal ai-services]# ./bin/ai-services application create temp --template rag --params "ui.ort=12312"
Error: failed to load params for application: unsupported parameter: ui.ort
```

Signed-off-by: sagarwal-ibm <sagarwal@ibm.com>